// Generated by zhangbaogang
// https://github.com/bogong/SJTULib-PAC/lib.pac

var domains = {
  "sjtu.edu.cn":1,
  "zhizhen.com":1,
  "wanfangdata.com.cn":1,
  "ip.cn":1,
  "duxiu.com":1,
  "cnki.net":1
};

var proxy =  "PROXY inproxy.sjtu.edu.cn:8000";
var direct = 'DIRECT;';
var hasOwnProperty = Object.hasOwnProperty;

function FindProxyForURL(url, host) {
    var suffix;
    var pos = host.lastIndexOf('.');
    pos = host.lastIndexOf('.', pos - 1);
    while(1) {
        if (pos <= 0) {
            if (hasOwnProperty.call(domains, host)) {
                return proxy;
            } else {
                return direct;
            }
        }
        suffix = host.substring(pos + 1);
        if (hasOwnProperty.call(domains, suffix)) {
            return proxy;
        }
        pos = host.lastIndexOf('.', pos - 1);
    }
}
